### ISSUE TITLE
gulp bootstrap fails on Ubuntu Trusty

### ISSUE THREAD

**Issue by louy2** [yan-foto/neutron#21]
``` shell
$ gulp bootstrap
[03:31:02] Failed to load external module babel-core/register
[03:31:02] Failed to load external module babel/register
/home/vagrant/IronLock/electron-ui/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { let gulp = require('gulp');
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/home/vagrant/.nvm/versions/node/v4.1.1/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/vagrant/.nvm/versions/node/v4.1.1/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/home/vagrant/.nvm/versions/node/v4.1.1/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

Seems a `use strict` is lost?

**Comment by yan-foto** [comment]
see #16
