### ISSUE TITLE
Errors on windows with npm install and yo

### ISSUE THREAD

**Issue by SelaO** [yan-foto/neutron#25]
I'm getting many errors on windows 10, first it wanted python 2.7 (why not 3?) then it complains about .net framework 2 even though I have the latest one installed. 

What are all the prerequisites for this project to work?

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 1/2/2018 5:13:39 PM.
Project "C:\electron\neutron\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\electron\neutron\node_modules\node-sass\build\binding.sln" (1) is building "C:\electron\neutron\node_module
s\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
Project "C:\electron\neutron\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "C:\electron\neutro
n\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
C:\electron\neutron\node_modules\node-sass\build\src\libsass.vcxproj(20,3): error MSB4019: The imported project "C:\Mic
rosoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.
Done Building Project "C:\electron\neutron\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILE
D.

Done Building Project "C:\electron\neutron\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) --
FAILED.

Done Building Project "C:\electron\neutron\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"C:\electron\neutron\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"C:\electron\neutron\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"C:\electron\neutron\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
  C:\electron\neutron\node_modules\node-sass\build\src\libsass.vcxproj(20,3): error MSB4019: The imported project "C:\M
icrosoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the f
ile exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.84
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\electron\neutron\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\electron\\neutron\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\electron\neutron\node_modules\node-sass
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SO\AppData\Roaming\npm-cache\_logs\2018-01-02T15_13_43_938Z-debug.log
```

**Comment by yan-foto** [comment]
As you can see, this is a `node-sass` issue and does not really relate to `neutron`. On the other hand, I haven't updated the project in more than 2 years and will not be able to maintain it anymore. So the chances are that the dependencies are outdated.

**Comment by SelaO** [comment]
I just noticed that it's old. 

Do you have a recommendation for a similar project?
